# Generated by Django 5.2.6 on 2025-09-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField(db_column='D_O_P')),
                ('description', models.TextField(db_column='Description')),
                ('active', models.BooleanField()),
            ],
        ),
    ]
